version: '3'
services:
  node-red:
    build: .
    restart: always
    init: true
    network_mode: host
#    ports:
#      - 1880:1880
    container_name: node-red
    user: "${UID}:${GID}"
    volumes:
      - ./data:/data
      - /var/run/dbus:/var/run/dbus
    env_file: .env

